dataSource:
  driverClassName: com.mysql.cj.jdbc.Driver
  dbCreate: update
  username: root
  password: '123456789'

environments:
  development:
    dataSource:
      dbCreate: update
      url: "jdbc:mysql://127.0.0.1:3306/userPortal?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
